package org.dummy.brms.dummy_brms.mybatis.pojo.dumb_brms;

import java.util.ArrayList;
import java.util.List;

public class InputDataTypesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    public InputDataTypesExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(Long value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(Long value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(Long value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(Long value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(Long value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(Long value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<Long> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<Long> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(Long value1, Long value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(Long value1, Long value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andDataTypeNameIsNull() {
            addCriterion("data_type_name is null");
            return (Criteria) this;
        }

        public Criteria andDataTypeNameIsNotNull() {
            addCriterion("data_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andDataTypeNameEqualTo(String value) {
            addCriterion("data_type_name =", value, "dataTypeName");
            return (Criteria) this;
        }

        public Criteria andDataTypeNameNotEqualTo(String value) {
            addCriterion("data_type_name <>", value, "dataTypeName");
            return (Criteria) this;
        }

        public Criteria andDataTypeNameGreaterThan(String value) {
            addCriterion("data_type_name >", value, "dataTypeName");
            return (Criteria) this;
        }

        public Criteria andDataTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("data_type_name >=", value, "dataTypeName");
            return (Criteria) this;
        }

        public Criteria andDataTypeNameLessThan(String value) {
            addCriterion("data_type_name <", value, "dataTypeName");
            return (Criteria) this;
        }

        public Criteria andDataTypeNameLessThanOrEqualTo(String value) {
            addCriterion("data_type_name <=", value, "dataTypeName");
            return (Criteria) this;
        }

        public Criteria andDataTypeNameLike(String value) {
            addCriterion("data_type_name like", value, "dataTypeName");
            return (Criteria) this;
        }

        public Criteria andDataTypeNameNotLike(String value) {
            addCriterion("data_type_name not like", value, "dataTypeName");
            return (Criteria) this;
        }

        public Criteria andDataTypeNameIn(List<String> values) {
            addCriterion("data_type_name in", values, "dataTypeName");
            return (Criteria) this;
        }

        public Criteria andDataTypeNameNotIn(List<String> values) {
            addCriterion("data_type_name not in", values, "dataTypeName");
            return (Criteria) this;
        }

        public Criteria andDataTypeNameBetween(String value1, String value2) {
            addCriterion("data_type_name between", value1, value2, "dataTypeName");
            return (Criteria) this;
        }

        public Criteria andDataTypeNameNotBetween(String value1, String value2) {
            addCriterion("data_type_name not between", value1, value2, "dataTypeName");
            return (Criteria) this;
        }

        public Criteria andDataTypeDescrIsNull() {
            addCriterion("data_type_descr is null");
            return (Criteria) this;
        }

        public Criteria andDataTypeDescrIsNotNull() {
            addCriterion("data_type_descr is not null");
            return (Criteria) this;
        }

        public Criteria andDataTypeDescrEqualTo(String value) {
            addCriterion("data_type_descr =", value, "dataTypeDescr");
            return (Criteria) this;
        }

        public Criteria andDataTypeDescrNotEqualTo(String value) {
            addCriterion("data_type_descr <>", value, "dataTypeDescr");
            return (Criteria) this;
        }

        public Criteria andDataTypeDescrGreaterThan(String value) {
            addCriterion("data_type_descr >", value, "dataTypeDescr");
            return (Criteria) this;
        }

        public Criteria andDataTypeDescrGreaterThanOrEqualTo(String value) {
            addCriterion("data_type_descr >=", value, "dataTypeDescr");
            return (Criteria) this;
        }

        public Criteria andDataTypeDescrLessThan(String value) {
            addCriterion("data_type_descr <", value, "dataTypeDescr");
            return (Criteria) this;
        }

        public Criteria andDataTypeDescrLessThanOrEqualTo(String value) {
            addCriterion("data_type_descr <=", value, "dataTypeDescr");
            return (Criteria) this;
        }

        public Criteria andDataTypeDescrLike(String value) {
            addCriterion("data_type_descr like", value, "dataTypeDescr");
            return (Criteria) this;
        }

        public Criteria andDataTypeDescrNotLike(String value) {
            addCriterion("data_type_descr not like", value, "dataTypeDescr");
            return (Criteria) this;
        }

        public Criteria andDataTypeDescrIn(List<String> values) {
            addCriterion("data_type_descr in", values, "dataTypeDescr");
            return (Criteria) this;
        }

        public Criteria andDataTypeDescrNotIn(List<String> values) {
            addCriterion("data_type_descr not in", values, "dataTypeDescr");
            return (Criteria) this;
        }

        public Criteria andDataTypeDescrBetween(String value1, String value2) {
            addCriterion("data_type_descr between", value1, value2, "dataTypeDescr");
            return (Criteria) this;
        }

        public Criteria andDataTypeDescrNotBetween(String value1, String value2) {
            addCriterion("data_type_descr not between", value1, value2, "dataTypeDescr");
            return (Criteria) this;
        }

        public Criteria andFlgDeletedIsNull() {
            addCriterion("flg_deleted is null");
            return (Criteria) this;
        }

        public Criteria andFlgDeletedIsNotNull() {
            addCriterion("flg_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andFlgDeletedEqualTo(Boolean value) {
            addCriterion("flg_deleted =", value, "flgDeleted");
            return (Criteria) this;
        }

        public Criteria andFlgDeletedNotEqualTo(Boolean value) {
            addCriterion("flg_deleted <>", value, "flgDeleted");
            return (Criteria) this;
        }

        public Criteria andFlgDeletedGreaterThan(Boolean value) {
            addCriterion("flg_deleted >", value, "flgDeleted");
            return (Criteria) this;
        }

        public Criteria andFlgDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("flg_deleted >=", value, "flgDeleted");
            return (Criteria) this;
        }

        public Criteria andFlgDeletedLessThan(Boolean value) {
            addCriterion("flg_deleted <", value, "flgDeleted");
            return (Criteria) this;
        }

        public Criteria andFlgDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("flg_deleted <=", value, "flgDeleted");
            return (Criteria) this;
        }

        public Criteria andFlgDeletedIn(List<Boolean> values) {
            addCriterion("flg_deleted in", values, "flgDeleted");
            return (Criteria) this;
        }

        public Criteria andFlgDeletedNotIn(List<Boolean> values) {
            addCriterion("flg_deleted not in", values, "flgDeleted");
            return (Criteria) this;
        }

        public Criteria andFlgDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("flg_deleted between", value1, value2, "flgDeleted");
            return (Criteria) this;
        }

        public Criteria andFlgDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("flg_deleted not between", value1, value2, "flgDeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated do_not_delete_during_merge Thu Jan 30 20:11:38 CET 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}