package org.dummy.brms.dummy_brms.mybatis.pojo.dumb_brms;

public class OutputDataTypes extends OutputDataTypesKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dumb_brms.output_data_types.data_type_descr
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    private String dataTypeDescr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dumb_brms.output_data_types.flg_deleted
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    private Boolean flgDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dumb_brms.output_data_types.data_type_descr
     *
     * @return the value of dumb_brms.output_data_types.data_type_descr
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    public String getDataTypeDescr() {
        return dataTypeDescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dumb_brms.output_data_types.data_type_descr
     *
     * @param dataTypeDescr the value for dumb_brms.output_data_types.data_type_descr
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    public void setDataTypeDescr(String dataTypeDescr) {
        this.dataTypeDescr = dataTypeDescr == null ? null : dataTypeDescr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dumb_brms.output_data_types.flg_deleted
     *
     * @return the value of dumb_brms.output_data_types.flg_deleted
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    public Boolean getFlgDeleted() {
        return flgDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dumb_brms.output_data_types.flg_deleted
     *
     * @param flgDeleted the value for dumb_brms.output_data_types.flg_deleted
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    public void setFlgDeleted(Boolean flgDeleted) {
        this.flgDeleted = flgDeleted;
    }
}