package org.dummy.brms.dummy_brms.mybatis.pojo.dumb_brms;

public class ProjectsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dumb_brms.projects.id
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dumb_brms.projects.user_id
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dumb_brms.projects.id
     *
     * @return the value of dumb_brms.projects.id
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dumb_brms.projects.id
     *
     * @param id the value for dumb_brms.projects.id
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dumb_brms.projects.user_id
     *
     * @return the value of dumb_brms.projects.user_id
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dumb_brms.projects.user_id
     *
     * @param userId the value for dumb_brms.projects.user_id
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}