package org.dummy.brms.dummy_brms.mybatis.pojo.dumb_brms;

import java.util.Date;

public class Projects extends ProjectsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dumb_brms.projects.project_name
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dumb_brms.projects.last_update
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    private Date lastUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dumb_brms.projects.creation_datetime
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    private Date creationDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dumb_brms.projects.project_name
     *
     * @return the value of dumb_brms.projects.project_name
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dumb_brms.projects.project_name
     *
     * @param projectName the value for dumb_brms.projects.project_name
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dumb_brms.projects.last_update
     *
     * @return the value of dumb_brms.projects.last_update
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dumb_brms.projects.last_update
     *
     * @param lastUpdate the value for dumb_brms.projects.last_update
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dumb_brms.projects.creation_datetime
     *
     * @return the value of dumb_brms.projects.creation_datetime
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    public Date getCreationDatetime() {
        return creationDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dumb_brms.projects.creation_datetime
     *
     * @param creationDatetime the value for dumb_brms.projects.creation_datetime
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    public void setCreationDatetime(Date creationDatetime) {
        this.creationDatetime = creationDatetime;
    }
}