package org.dummy.brms.dummy_brms.mybatis.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.dummy.brms.dummy_brms.mybatis.pojo.dumb_brms.InputDataTypes;
import org.dummy.brms.dummy_brms.mybatis.pojo.dumb_brms.InputDataTypesExample;
import org.dummy.brms.dummy_brms.mybatis.pojo.dumb_brms.InputDataTypesKey;

public interface InputDataTypesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    long countByExample(InputDataTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    int deleteByExample(InputDataTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    int deleteByPrimaryKey(InputDataTypesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    int insert(InputDataTypes row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    int insertSelective(InputDataTypes row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    List<InputDataTypes> selectByExample(InputDataTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    InputDataTypes selectByPrimaryKey(InputDataTypesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    int updateByExampleSelective(@Param("row") InputDataTypes row, @Param("example") InputDataTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    int updateByExample(@Param("row") InputDataTypes row, @Param("example") InputDataTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    int updateByPrimaryKeySelective(InputDataTypes row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    int updateByPrimaryKey(InputDataTypes row);
}