package org.dummy.brms.dummy_brms.mybatis.mappers;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;
import org.dummy.brms.dummy_brms.mybatis.pojo.dumb_brms.InputDataTypes;
import org.dummy.brms.dummy_brms.mybatis.pojo.dumb_brms.InputDataTypesExample.Criteria;
import org.dummy.brms.dummy_brms.mybatis.pojo.dumb_brms.InputDataTypesExample.Criterion;
import org.dummy.brms.dummy_brms.mybatis.pojo.dumb_brms.InputDataTypesExample;

public class InputDataTypesSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    public String countByExample(InputDataTypesExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("dumb_brms.input_data_types");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    public String deleteByExample(InputDataTypesExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("dumb_brms.input_data_types");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    public String insertSelective(InputDataTypes row) {
        SQL sql = new SQL();
        sql.INSERT_INTO("dumb_brms.input_data_types");
        
        if (row.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=BIGINT}");
        }
        
        if (row.getProjectId() != null) {
            sql.VALUES("project_id", "#{projectId,jdbcType=BIGINT}");
        }
        
        if (row.getDataTypeName() != null) {
            sql.VALUES("data_type_name", "#{dataTypeName,jdbcType=VARCHAR}");
        }
        
        if (row.getDataTypeDescr() != null) {
            sql.VALUES("data_type_descr", "#{dataTypeDescr,jdbcType=VARCHAR}");
        }
        
        if (row.getFlgDeleted() != null) {
            sql.VALUES("flg_deleted", "#{flgDeleted,jdbcType=BIT}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    public String selectByExample(InputDataTypesExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("user_id");
        } else {
            sql.SELECT("user_id");
        }
        sql.SELECT("project_id");
        sql.SELECT("data_type_name");
        sql.SELECT("data_type_descr");
        sql.SELECT("flg_deleted");
        sql.FROM("dumb_brms.input_data_types");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        InputDataTypes row = (InputDataTypes) parameter.get("row");
        InputDataTypesExample example = (InputDataTypesExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("dumb_brms.input_data_types");
        
        if (row.getUserId() != null) {
            sql.SET("user_id = #{row.userId,jdbcType=BIGINT}");
        }
        
        if (row.getProjectId() != null) {
            sql.SET("project_id = #{row.projectId,jdbcType=BIGINT}");
        }
        
        if (row.getDataTypeName() != null) {
            sql.SET("data_type_name = #{row.dataTypeName,jdbcType=VARCHAR}");
        }
        
        if (row.getDataTypeDescr() != null) {
            sql.SET("data_type_descr = #{row.dataTypeDescr,jdbcType=VARCHAR}");
        }
        
        if (row.getFlgDeleted() != null) {
            sql.SET("flg_deleted = #{row.flgDeleted,jdbcType=BIT}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("dumb_brms.input_data_types");
        
        sql.SET("user_id = #{row.userId,jdbcType=BIGINT}");
        sql.SET("project_id = #{row.projectId,jdbcType=BIGINT}");
        sql.SET("data_type_name = #{row.dataTypeName,jdbcType=VARCHAR}");
        sql.SET("data_type_descr = #{row.dataTypeDescr,jdbcType=VARCHAR}");
        sql.SET("flg_deleted = #{row.flgDeleted,jdbcType=BIT}");
        
        InputDataTypesExample example = (InputDataTypesExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    public String updateByPrimaryKeySelective(InputDataTypes row) {
        SQL sql = new SQL();
        sql.UPDATE("dumb_brms.input_data_types");
        
        if (row.getDataTypeDescr() != null) {
            sql.SET("data_type_descr = #{dataTypeDescr,jdbcType=VARCHAR}");
        }
        
        if (row.getFlgDeleted() != null) {
            sql.SET("flg_deleted = #{flgDeleted,jdbcType=BIT}");
        }
        
        sql.WHERE("user_id = #{userId,jdbcType=BIGINT}");
        sql.WHERE("project_id = #{projectId,jdbcType=BIGINT}");
        sql.WHERE("data_type_name = #{dataTypeName,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    protected void applyWhere(SQL sql, InputDataTypesExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}