package org.dummy.brms.dummy_brms.mybatis.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.dummy.brms.dummy_brms.mybatis.pojo.dumb_brms.InputDataTypes;
import org.dummy.brms.dummy_brms.mybatis.pojo.dumb_brms.InputDataTypesExample;
import org.dummy.brms.dummy_brms.mybatis.pojo.dumb_brms.InputDataTypesKey;

public interface InputDataTypesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    @SelectProvider(type=InputDataTypesSqlProvider.class, method="countByExample")
    long countByExample(InputDataTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    @DeleteProvider(type=InputDataTypesSqlProvider.class, method="deleteByExample")
    int deleteByExample(InputDataTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    @Delete({
        "delete from dumb_brms.input_data_types",
        "where user_id = #{userId,jdbcType=BIGINT}",
          "and project_id = #{projectId,jdbcType=BIGINT}",
          "and data_type_name = #{dataTypeName,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(InputDataTypesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    @Insert({
        "insert into dumb_brms.input_data_types (user_id, project_id, ",
        "data_type_name, data_type_descr, ",
        "flg_deleted)",
        "values (#{userId,jdbcType=BIGINT}, #{projectId,jdbcType=BIGINT}, ",
        "#{dataTypeName,jdbcType=VARCHAR}, #{dataTypeDescr,jdbcType=VARCHAR}, ",
        "#{flgDeleted,jdbcType=BIT})"
    })
    int insert(InputDataTypes row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    @InsertProvider(type=InputDataTypesSqlProvider.class, method="insertSelective")
    int insertSelective(InputDataTypes row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    @SelectProvider(type=InputDataTypesSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="project_id", property="projectId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="data_type_name", property="dataTypeName", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="data_type_descr", property="dataTypeDescr", jdbcType=JdbcType.VARCHAR),
        @Result(column="flg_deleted", property="flgDeleted", jdbcType=JdbcType.BIT)
    })
    List<InputDataTypes> selectByExample(InputDataTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    @Select({
        "select",
        "user_id, project_id, data_type_name, data_type_descr, flg_deleted",
        "from dumb_brms.input_data_types",
        "where user_id = #{userId,jdbcType=BIGINT}",
          "and project_id = #{projectId,jdbcType=BIGINT}",
          "and data_type_name = #{dataTypeName,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="project_id", property="projectId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="data_type_name", property="dataTypeName", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="data_type_descr", property="dataTypeDescr", jdbcType=JdbcType.VARCHAR),
        @Result(column="flg_deleted", property="flgDeleted", jdbcType=JdbcType.BIT)
    })
    InputDataTypes selectByPrimaryKey(InputDataTypesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    @UpdateProvider(type=InputDataTypesSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("row") InputDataTypes row, @Param("example") InputDataTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    @UpdateProvider(type=InputDataTypesSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("row") InputDataTypes row, @Param("example") InputDataTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    @UpdateProvider(type=InputDataTypesSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(InputDataTypes row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.input_data_types
     *
     * @mbg.generated Thu Jan 30 20:53:11 CET 2025
     */
    @Update({
        "update dumb_brms.input_data_types",
        "set data_type_descr = #{dataTypeDescr,jdbcType=VARCHAR},",
          "flg_deleted = #{flgDeleted,jdbcType=BIT}",
        "where user_id = #{userId,jdbcType=BIGINT}",
          "and project_id = #{projectId,jdbcType=BIGINT}",
          "and data_type_name = #{dataTypeName,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(InputDataTypes row);
}