package org.dummy.brms.dummy_brms.mybatis.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.dummy.brms.dummy_brms.mybatis.pojo.dumb_brms.OutputDataTypes;
import org.dummy.brms.dummy_brms.mybatis.pojo.dumb_brms.OutputDataTypesExample;
import org.dummy.brms.dummy_brms.mybatis.pojo.dumb_brms.OutputDataTypesKey;

public interface OutputDataTypesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.output_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    long countByExample(OutputDataTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.output_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    int deleteByExample(OutputDataTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.output_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    int deleteByPrimaryKey(OutputDataTypesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.output_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    int insert(OutputDataTypes row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.output_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    int insertSelective(OutputDataTypes row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.output_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    List<OutputDataTypes> selectByExample(OutputDataTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.output_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    OutputDataTypes selectByPrimaryKey(OutputDataTypesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.output_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    int updateByExampleSelective(@Param("row") OutputDataTypes row, @Param("example") OutputDataTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.output_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    int updateByExample(@Param("row") OutputDataTypes row, @Param("example") OutputDataTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.output_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    int updateByPrimaryKeySelective(OutputDataTypes row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dumb_brms.output_data_types
     *
     * @mbg.generated Thu Jan 30 20:11:38 CET 2025
     */
    int updateByPrimaryKey(OutputDataTypes row);
}